name: Build MAUI iOS

on:
  workflow_dispatch: 

jobs:
  build-ios:
    # Usamos macos-15 (Trae Xcode 16 que es 100% compatible con .NET 9)
    runs-on: macos-15 
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Clonar el código
      uses: actions/checkout@v4

    - name: Configurar .NET 9 (Versión Estable)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Instalar motor de MAUI
      run: dotnet workload install maui

    - name: Compilar y Generar .ipa (Sin firma)
      run: dotnet publish VerticeMobile.csproj -f net9.0-ios -c Release -p:RuntimeIdentifier=ios-arm64 -p:EnableCodeSigning=false -p:BuildIpa=true

    - name: Subir el archivo descargable
      uses: actions/upload-artifact@v4
      with:
        name: VerticeApp-iOS
        path: '**/*.ipa'
