name: Build MAUI iOS (Gratis)

# Esto permite que el script no corra solo, sino que vos apretes un botón para compilar
on:
  workflow_dispatch: 

jobs:
  build-ios:
    # Usamos macos-15 para tener el Xcode moderno
    runs-on: macos-15 
    
    # Silenciamos la advertencia de Node.js
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Clonar el código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 

    - name: Instalar motor de MAUI
      run: dotnet workload install maui

    - name: Forzar Bypass de Xcode (El parche real)
      # Crea un archivo de propiedades globales que MSBuild está obligado a leer y obedecer
      run: echo "<Project><PropertyGroup><VerifyXcodeVersion>false</VerifyXcodeVersion></PropertyGroup></Project>" > Directory.Build.props

    - name: Compilar y Generar .ipa (Sin firma)
      # Ya no hace falta el parámetro por consola, el archivo de arriba hace el trabajo pesado
      run: dotnet publish VerticeMobile.csproj -f net10.0-ios -c Release -p:RuntimeIdentifier=ios-arm64 -p:EnableCodeSigning=false -p:BuildIpa=true

    - name: Subir el archivo descargable
      uses: actions/upload-artifact@v4
      with:
        name: VerticeApp-iOS
        path: '**/*.ipa'
